[project]
name = "emojisync"
version = "0.1.0"
description = "Emotion detector using Py-feat"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "notebook>=7.5.1",
    "opencv-python>=4.8.1.78",
    "py-feat>=0.6.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
